"""initial

Revision ID: 972c34565a6b
Create Date: 2024-07-11 01:19:29.774096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "972c34565a6b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "days",
        sa.Column("day_id", sa.Integer(), nullable=False),
        sa.Column("day_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("day_id"),
    )
    op.create_table(
        "groups",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("custom", sa.Boolean(), nullable=True),
        sa.Column("group_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_table(
        "users",
        sa.Column("tg_id", sa.String(), nullable=False),
        sa.Column("show_help", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    op.create_table(
        "zones",
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("zone_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("zone_id"),
    )
    op.create_table(
        "hours",
        sa.Column("hour_id", sa.Integer(), nullable=False),
        sa.Column("day_id", sa.Integer(), nullable=True),
        sa.Column("hour", sa.Integer(), nullable=True),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["days.day_id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zones.zone_id"],
        ),
        sa.PrimaryKeyConstraint("hour_id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("user_tg_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_tg_id"],
            ["users.tg_id"],
        ),
        sa.PrimaryKeyConstraint("user_tg_id", "group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    op.drop_table("hours")
    op.drop_table("zones")
    op.drop_table("users")
    op.drop_table("groups")
    op.drop_table("days")
    # ### end Alembic commands ###
