"""notification_time_update

Revision ID: d5b854f2b9d3
Revises: 31d1c6ff6784
Create Date: 2024-08-16 17:24:22.411795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5b854f2b9d3"
down_revision: Union[str, None] = "31d1c6ff6784"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("days", schema=None) as batch_op:
        batch_op.alter_column("day_name", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.alter_column("custom", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("group_name", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("hours", schema=None) as batch_op:
        batch_op.alter_column("day_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("hour", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("zone_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("group_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("remind_before", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("suppress_night", sa.Boolean(), nullable=False))
        batch_op.alter_column("show_help", existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table("zones", schema=None) as batch_op:
        batch_op.alter_column("zone_name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("zones", schema=None) as batch_op:
        batch_op.alter_column("zone_name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("show_help", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.drop_column("suppress_night")
        batch_op.drop_column("remind_before")

    with op.batch_alter_table("hours", schema=None) as batch_op:
        batch_op.alter_column("group_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("zone_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("hour", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("day_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.alter_column("group_name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("custom", existing_type=sa.BOOLEAN(), nullable=True)

    with op.batch_alter_table("days", schema=None) as batch_op:
        batch_op.alter_column("day_name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
